/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CatalogArtifact {
  metadata: CatalogMetadata;
  nodes: {
    [k: string]: CatalogTable;
  };
  sources: {
    [k: string]: CatalogTable1;
  };
  errors?: string[] | null;
  _compile_results?: unknown;
}
export interface CatalogMetadata {
  dbt_schema_version?: string;
  dbt_version?: string;
  generated_at?: string;
  invocation_id?: string | null;
  invocation_started_at?: string | null;
  env?: {
    [k: string]: string;
  };
}
export interface CatalogTable {
  metadata: TableMetadata;
  columns: {
    [k: string]: ColumnMetadata;
  };
  stats: {
    [k: string]: StatsItem;
  };
  unique_id?: string | null;
}
export interface TableMetadata {
  type: string;
  schema: string;
  name: string;
  database?: string | null;
  comment?: string | null;
  owner?: string | null;
}
export interface ColumnMetadata {
  type: string;
  index: number;
  name: string;
  comment?: string | null;
}
export interface StatsItem {
  id: string;
  label: string;
  value: boolean | string | number | null;
  include: boolean;
  description?: string | null;
}
export interface CatalogTable1 {
  metadata: TableMetadata1;
  columns: {
    [k: string]: ColumnMetadata1;
  };
  stats: {
    [k: string]: StatsItem1;
  };
  unique_id?: string | null;
}
export interface TableMetadata1 {
  type: string;
  schema: string;
  name: string;
  database?: string | null;
  comment?: string | null;
  owner?: string | null;
}
export interface ColumnMetadata1 {
  type: string;
  index: number;
  name: string;
  comment?: string | null;
}
export interface StatsItem1 {
  id: string;
  label: string;
  value: boolean | string | number | null;
  include: boolean;
  description?: string | null;
}
