/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * FreshnessExecutionResultArtifact(metadata: dbt.contracts.results.FreshnessMetadata, results: Sequence[Union[dbt.contracts.results.SourceFreshnessRuntimeError, dbt.contracts.results.SourceFreshnessOutput]], elapsed_time: float)
 */
export interface HttpsSchemasGetdbtComDbtSourcesV2Json {
  metadata: FreshnessMetadata;
  results: (SourceFreshnessRuntimeError | SourceFreshnessOutput)[];
  elapsed_time: number;
}
/**
 * FreshnessMetadata(dbt_schema_version: str = <factory>, dbt_version: str = '0.21.0rc1', generated_at: datetime.datetime = <factory>, invocation_id: Union[str, NoneType] = <factory>, env: Dict[str, str] = <factory>)
 *
 * This interface was referenced by `HttpsSchemasGetdbtComDbtSourcesV2Json`'s JSON-Schema
 * via the `definition` "FreshnessMetadata".
 */
export interface FreshnessMetadata {
  dbt_schema_version?: string;
  dbt_version?: string;
  generated_at?: string;
  invocation_id?: string | null;
  env?: {
    [k: string]: string;
  };
}
/**
 * SourceFreshnessRuntimeError(unique_id: str, error: Union[str, int, NoneType], status: dbt.contracts.results.FreshnessErrorEnum)
 *
 * This interface was referenced by `HttpsSchemasGetdbtComDbtSourcesV2Json`'s JSON-Schema
 * via the `definition` "SourceFreshnessRuntimeError".
 */
export interface SourceFreshnessRuntimeError {
  unique_id: string;
  error?: string | number | null;
  status: "runtime error";
}
/**
 * SourceFreshnessOutput(unique_id: str, max_loaded_at: datetime.datetime, snapshotted_at: datetime.datetime, max_loaded_at_time_ago_in_s: float, status: dbt.contracts.results.FreshnessStatus, criteria: dbt.contracts.graph.unparsed.FreshnessThreshold, adapter_response: Dict[str, Any], timing: List[dbt.contracts.results.TimingInfo], thread_id: str, execution_time: float)
 *
 * This interface was referenced by `HttpsSchemasGetdbtComDbtSourcesV2Json`'s JSON-Schema
 * via the `definition` "SourceFreshnessOutput".
 */
export interface SourceFreshnessOutput {
  unique_id: string;
  max_loaded_at: string;
  snapshotted_at: string;
  max_loaded_at_time_ago_in_s: number;
  status: "pass" | "warn" | "error" | "runtime error";
  criteria: FreshnessThreshold;
  adapter_response: {
    [k: string]: unknown;
  };
  timing: TimingInfo[];
  thread_id: string;
  execution_time: number;
}
/**
 * FreshnessThreshold(warn_after: Union[dbt.contracts.graph.unparsed.Time, NoneType] = None, error_after: Union[dbt.contracts.graph.unparsed.Time, NoneType] = None, filter: Union[str, NoneType] = None)
 *
 * This interface was referenced by `HttpsSchemasGetdbtComDbtSourcesV2Json`'s JSON-Schema
 * via the `definition` "FreshnessThreshold".
 */
export interface FreshnessThreshold {
  warn_after?: Time | null;
  error_after?: Time | null;
  filter?: string | null;
}
/**
 * Time(count: int, period: dbt.contracts.graph.unparsed.TimePeriod)
 *
 * This interface was referenced by `HttpsSchemasGetdbtComDbtSourcesV2Json`'s JSON-Schema
 * via the `definition` "Time".
 */
export interface Time {
  count: number;
  period: "minute" | "hour" | "day";
}
/**
 * TimingInfo(name: str, started_at: Union[datetime.datetime, NoneType] = None, completed_at: Union[datetime.datetime, NoneType] = None)
 *
 * This interface was referenced by `HttpsSchemasGetdbtComDbtSourcesV2Json`'s JSON-Schema
 * via the `definition` "TimingInfo".
 */
export interface TimingInfo {
  name: string;
  started_at?: string | null;
  completed_at?: string | null;
}
