/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FreshnessExecutionResultArtifact {
  metadata: FreshnessMetadata;
  results: (SourceFreshnessRuntimeError | SourceFreshnessOutput)[];
  elapsed_time: number;
}
export interface FreshnessMetadata {
  dbt_schema_version?: string;
  dbt_version?: string;
  generated_at?: string;
  invocation_id?: string | null;
  env?: {
    [k: string]: string;
  };
}
export interface SourceFreshnessRuntimeError {
  unique_id: string;
  error: string | number | null;
  status: "runtime error";
}
export interface SourceFreshnessOutput {
  unique_id: string;
  max_loaded_at: string;
  snapshotted_at: string;
  max_loaded_at_time_ago_in_s: number;
  status: "pass" | "warn" | "error" | "runtime error";
  criteria: FreshnessThreshold;
  adapter_response: {
    [k: string]: unknown;
  };
  timing: TimingInfo[];
  thread_id: string;
  execution_time: number;
}
export interface FreshnessThreshold {
  warn_after?: Time | null;
  error_after?: Time1 | null;
  filter?: string | null;
}
export interface Time {
  count?: number | null;
  period?: ("minute" | "hour" | "day") | null;
}
export interface Time1 {
  count?: number | null;
  period?: ("minute" | "hour" | "day") | null;
}
export interface TimingInfo {
  name: string;
  started_at?: string | null;
  completed_at?: string | null;
}
