/* AUTO-GENERATED by scripts/build-tokens.mjs — canvas/chart hex mirrors of CSS tokens */
export type ThemeMode = "light" | "dark";

export const THEME_HEX_LIGHT = {
  accent: "#635BFF",
  text: "#171C28",
  textSoft: "#6B7385",
  bg: "#F6F7FB",
  bgSoft: "#FFFFFF",
  borderDefault: "#D7DCE7",
  borderSubtle: "#E6E9F0",
  slate: "#64748B",
  rose: "#C0352B",
  mint: "#0F8A4B",
  amber: "#A56315",
} as const;

export const THEME_HEX_DARK = {
  accent: "#8A7CFF",
  text: "#F3F6FC",
  textSoft: "#98A3BC",
  bg: "#0D1120",
  bgSoft: "#151A2E",
  borderDefault: "#313A58",
  borderSubtle: "#262E47",
  slate: "#8690AA",
  rose: "#FF8D86",
  mint: "#59D38C",
  amber: "#F5B95C",
} as const;

export function getThemeHex(theme: ThemeMode) {
  return theme === "dark" ? THEME_HEX_DARK : THEME_HEX_LIGHT;
}

export const STATUS_HEX_LIGHT = {
  success: THEME_HEX_LIGHT.mint,
  error: THEME_HEX_LIGHT.rose,
  skipped: THEME_HEX_LIGHT.slate,
  "run error": THEME_HEX_LIGHT.rose,
  pass: THEME_HEX_LIGHT.mint,
  fail: THEME_HEX_LIGHT.rose,
  warn: THEME_HEX_LIGHT.amber,
  "no op": THEME_HEX_LIGHT.slate,
} as const;

export const STATUS_HEX_DARK = {
  success: THEME_HEX_DARK.mint,
  error: THEME_HEX_DARK.rose,
  skipped: THEME_HEX_DARK.slate,
  "run error": THEME_HEX_DARK.rose,
  pass: THEME_HEX_DARK.mint,
  fail: THEME_HEX_DARK.rose,
  warn: THEME_HEX_DARK.amber,
  "no op": THEME_HEX_DARK.slate,
} as const;

export const RESOURCE_TYPE_HEX_LIGHT: Record<string, string> = {
  "model": "#1D4ED8",
  "test": "#64748B",
  "seed": "#635BFF",
  "snapshot": "#D97706",
  "source": "#059669",
  "source_freshness": "#059669",
  "exposure": "#EA580C",
  "metric": "#DB2777",
  "semantic_model": "#0891B2",
  "analysis": "#64748B",
  "unit_test": "#64748B",
};

export const RESOURCE_TYPE_HEX_DARK: Record<string, string> = {
  "model": "#5c8deb",
  "test": "#8690aa",
  "seed": "#9588e8",
  "snapshot": "#d4a24a",
  "source": "#45c49a",
  "source_freshness": "#45c49a",
  "exposure": "#d9845c",
  "metric": "#d172ae",
  "semantic_model": "#3eb0c8",
  "analysis": "#8690aa",
  "unit_test": "#8690aa",
};

export const RESOURCE_TYPE_SOFT_FILL_LIGHT: Record<string, string> = {
  "model": "rgb(29 78 216 / 14%)",
  "test": "rgb(100 116 139 / 14%)",
  "seed": "rgb(99 91 255 / 14%)",
  "snapshot": "rgb(217 119 6 / 14%)",
  "source": "rgb(5 150 105 / 14%)",
  "source_freshness": "rgb(5 150 105 / 14%)",
  "exposure": "rgb(234 88 12 / 14%)",
  "metric": "rgb(219 39 119 / 14%)",
  "semantic_model": "rgb(8 145 178 / 14%)",
  "analysis": "rgb(100 116 139 / 14%)",
  "unit_test": "rgb(100 116 139 / 14%)",
};

export const RESOURCE_TYPE_SOFT_FILL_DARK: Record<string, string> = {
  "model": "rgb(92 141 235 / 22%)",
  "test": "rgb(134 144 170 / 20%)",
  "seed": "rgb(149 136 232 / 22%)",
  "snapshot": "rgb(212 162 74 / 22%)",
  "source": "rgb(69 196 154 / 20%)",
  "source_freshness": "rgb(69 196 154 / 20%)",
  "exposure": "rgb(217 132 92 / 22%)",
  "metric": "rgb(209 114 174 / 22%)",
  "semantic_model": "rgb(62 176 200 / 22%)",
  "analysis": "rgb(134 144 170 / 20%)",
  "unit_test": "rgb(134 144 170 / 20%)",
};

export function getResourceTypeHexMap(theme: ThemeMode): Record<string, string> {
  return theme === "dark" ? RESOURCE_TYPE_HEX_DARK : RESOURCE_TYPE_HEX_LIGHT;
}

export function getResourceTypeSoftFillMap(theme: ThemeMode): Record<string, string> {
  return theme === "dark" ? RESOURCE_TYPE_SOFT_FILL_DARK : RESOURCE_TYPE_SOFT_FILL_LIGHT;
}

export function getResourceTypeSoftFill(resourceType: string | undefined, theme: ThemeMode): string {
  const map = getResourceTypeSoftFillMap(theme);
  if (resourceType && map[resourceType]) return map[resourceType]!;
  return map["test"]!;
}

export const CANVAS_LIGHT = {
  rowStripe: "#F1F3F8",
  rowStripeHover: "#EEF0FF",
  labelText: "#171C28",
  metaText: "#6B7385",
  axisTick: "#64748B",
  gridLine: "#E6E9F0",
  barHoverStroke: "#635BFF",
  testFailStripe: "rgba(192, 53, 43, 0.9)",
  testSkipStripe: "rgba(165, 99, 21, 0.88)",
  hullStroke: "#B8C0D4",
  hullFill: "rgba(230, 233, 240, 0.35)",
} as const;

export const CANVAS_DARK = {
  rowStripe: "#101527",
  rowStripeHover: "#232845",
  labelText: "#F3F6FC",
  metaText: "#98A3BC",
  axisTick: "#8690AA",
  gridLine: "#262E47",
  barHoverStroke: "#8A7CFF",
  testFailStripe: "rgba(255, 141, 134, 0.88)",
  testSkipStripe: "rgba(245, 185, 92, 0.88)",
  hullStroke: "#465172",
  hullFill: "rgba(38, 46, 71, 0.4)",
} as const;

export function getCanvasColors(theme: ThemeMode) {
  return theme === "dark" ? CANVAS_DARK : CANVAS_LIGHT;
}
