/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WritableManifest {
  metadata: ManifestMetadata;
  /**
   * The nodes defined in the dbt project and its dependencies
   */
  nodes: {
    [k: string]:
      | AnalysisNode
      | SingularTestNode
      | HookNode
      | ModelNode
      | RPCNode
      | SqlNode
      | GenericTestNode
      | SnapshotNode
      | SeedNode;
  };
  /**
   * The sources defined in the dbt project and its dependencies
   */
  sources: {
    [k: string]: SourceDefinition;
  };
  /**
   * The macros defined in the dbt project and its dependencies
   */
  macros: {
    [k: string]: Macro;
  };
  /**
   * The docs defined in the dbt project and its dependencies
   */
  docs: {
    [k: string]: Documentation;
  };
  /**
   * The exposures defined in the dbt project and its dependencies
   */
  exposures: {
    [k: string]: Exposure;
  };
  /**
   * The metrics defined in the dbt project and its dependencies
   */
  metrics: {
    [k: string]: Metric;
  };
  /**
   * The groups defined in the dbt project
   */
  groups: {
    [k: string]: Group;
  };
  /**
   * The selectors defined in selectors.yml
   */
  selectors: {
    [k: string]: unknown;
  };
  /**
   * A mapping of the disabled nodes in the target
   */
  disabled: {
    [k: string]: (
      | AnalysisNode1
      | SingularTestNode1
      | HookNode1
      | ModelNode1
      | RPCNode1
      | SqlNode1
      | GenericTestNode1
      | SnapshotNode1
      | SeedNode1
      | SourceDefinition1
      | Exposure1
      | Metric1
      | SavedQuery
      | SemanticModel
    )[];
  } | null;
  /**
   * A mapping from child nodes to their dependencies
   */
  parent_map: {
    [k: string]: string[];
  } | null;
  /**
   * A mapping from parent nodes to their dependents
   */
  child_map: {
    [k: string]: string[];
  } | null;
  /**
   * A mapping from group names to their nodes
   */
  group_map: {
    [k: string]: string[];
  } | null;
  /**
   * The saved queries defined in the dbt project
   */
  saved_queries: {
    [k: string]: SavedQuery1;
  };
  /**
   * The semantic models defined in the dbt project
   */
  semantic_models: {
    [k: string]: SemanticModel1;
  };
}
/**
 * Metadata about the manifest
 */
export interface ManifestMetadata {
  dbt_schema_version?: string;
  dbt_version?: string;
  generated_at?: string;
  invocation_id?: string | null;
  env?: {
    [k: string]: string;
  };
  /**
   * Name of the root project
   */
  project_name?: string | null;
  /**
   * A unique identifier for the project, hashed from the project name
   */
  project_id?: string | null;
  /**
   * A unique identifier for the user
   */
  user_id?: string | null;
  /**
   * Whether dbt is configured to send anonymous usage statistics
   */
  send_anonymous_usage_stats?: boolean | null;
  /**
   * The type name of the adapter
   */
  adapter_type?: string | null;
}
export interface AnalysisNode {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "analysis";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash;
  config?: NodeConfig;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs1;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE[];
  _pre_injected_sql?: string | null;
  contract?: Contract;
}
export interface FileHash {
  name: string;
  checksum: string;
}
export interface NodeConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook[];
  "pre-hook"?: Hook1[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs;
  contract?: ContractConfig;
  [k: string]: unknown;
}
export interface Hook {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook1 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs1 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE {
  id: string;
  sql: string;
}
export interface Contract {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface SingularTestNode {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "test";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash1;
  config?: TestConfig;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo1;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs2;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs1[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn1;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE1[];
  _pre_injected_sql?: string | null;
  contract?: Contract1;
}
export interface FileHash1 {
  name: string;
  checksum: string;
}
export interface TestConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  severity?: string;
  store_failures?: boolean | null;
  store_failures_as?: string | null;
  where?: string | null;
  limit?: number | null;
  fail_calc?: string;
  warn_if?: string;
  error_if?: string;
  [k: string]: unknown;
}
export interface ColumnInfo1 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint1[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint1 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs2 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs1 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn1 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE1 {
  id: string;
  sql: string;
}
export interface Contract1 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface HookNode {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "operation";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash2;
  config?: NodeConfig1;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo2;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs4;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs2[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn2;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE2[];
  _pre_injected_sql?: string | null;
  contract?: Contract2;
  index?: number | null;
}
export interface FileHash2 {
  name: string;
  checksum: string;
}
export interface NodeConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook2[];
  "pre-hook"?: Hook3[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs3;
  contract?: ContractConfig1;
  [k: string]: unknown;
}
export interface Hook2 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook3 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs3 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig1 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo2 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint2[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint2 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs4 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs2 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn2 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE2 {
  id: string;
  sql: string;
}
export interface Contract2 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface ModelNode {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "model";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash3;
  config?: ModelConfig;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo3;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs6;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs3[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn3;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE3[];
  _pre_injected_sql?: string | null;
  contract?: Contract3;
  access?: "private" | "protected" | "public";
  constraints?: ModelLevelConstraint[];
  version?: string | number | null;
  latest_version?: string | number | null;
  deprecation_date?: string | null;
  defer_relation?: DeferRelation | null;
}
export interface FileHash3 {
  name: string;
  checksum: string;
}
export interface ModelConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook4[];
  "pre-hook"?: Hook5[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs5;
  contract?: ContractConfig2;
  access?: "private" | "protected" | "public";
  [k: string]: unknown;
}
export interface Hook4 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook5 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs5 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig2 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo3 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint3[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint3 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs6 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs3 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn3 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE3 {
  id: string;
  sql: string;
}
export interface Contract3 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface ModelLevelConstraint {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
  columns?: string[];
}
export interface DeferRelation {
  database: string | null;
  schema: string;
  alias: string;
  relation_name: string | null;
}
export interface RPCNode {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "rpc";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash4;
  config?: NodeConfig2;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo4;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs8;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs4[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn4;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE4[];
  _pre_injected_sql?: string | null;
  contract?: Contract4;
}
export interface FileHash4 {
  name: string;
  checksum: string;
}
export interface NodeConfig2 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook6[];
  "pre-hook"?: Hook7[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs7;
  contract?: ContractConfig3;
  [k: string]: unknown;
}
export interface Hook6 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook7 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs7 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig3 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo4 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint4[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint4 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs8 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs4 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn4 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE4 {
  id: string;
  sql: string;
}
export interface Contract4 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface SqlNode {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "sql_operation";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash5;
  config?: NodeConfig3;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo5;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs10;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs5[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn5;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE5[];
  _pre_injected_sql?: string | null;
  contract?: Contract5;
}
export interface FileHash5 {
  name: string;
  checksum: string;
}
export interface NodeConfig3 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook8[];
  "pre-hook"?: Hook9[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs9;
  contract?: ContractConfig4;
  [k: string]: unknown;
}
export interface Hook8 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook9 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs9 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig4 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo5 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint5[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint5 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs10 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs5 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn5 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE5 {
  id: string;
  sql: string;
}
export interface Contract5 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface GenericTestNode {
  test_metadata: TestMetadata;
  database: string | null;
  schema: string;
  name: string;
  resource_type: "test";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash6;
  config?: TestConfig1;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo6;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs11;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs6[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn6;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE6[];
  _pre_injected_sql?: string | null;
  contract?: Contract6;
  column_name?: string | null;
  file_key_name?: string | null;
  attached_node?: string | null;
}
export interface TestMetadata {
  name: string;
  kwargs?: {
    [k: string]: unknown;
  };
  namespace?: string | null;
}
export interface FileHash6 {
  name: string;
  checksum: string;
}
export interface TestConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  severity?: string;
  store_failures?: boolean | null;
  store_failures_as?: string | null;
  where?: string | null;
  limit?: number | null;
  fail_calc?: string;
  warn_if?: string;
  error_if?: string;
  [k: string]: unknown;
}
export interface ColumnInfo6 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint6[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint6 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs11 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs6 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn6 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE6 {
  id: string;
  sql: string;
}
export interface Contract6 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface SnapshotNode {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "snapshot";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash7;
  config: SnapshotConfig;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo7;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs13;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs7[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn7;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE7[];
  _pre_injected_sql?: string | null;
  contract?: Contract7;
  defer_relation?: DeferRelation1 | null;
}
export interface FileHash7 {
  name: string;
  checksum: string;
}
export interface SnapshotConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook10[];
  "pre-hook"?: Hook11[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs12;
  contract?: ContractConfig5;
  strategy?: string | null;
  target_schema?: string | null;
  target_database?: string | null;
  updated_at?: string | null;
  check_cols?: string | string[] | null;
  [k: string]: unknown;
}
export interface Hook10 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook11 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs12 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig5 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo7 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint7[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint7 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs13 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs7 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn7 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE7 {
  id: string;
  sql: string;
}
export interface Contract7 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface DeferRelation1 {
  database: string | null;
  schema: string;
  alias: string;
  relation_name: string | null;
}
export interface SeedNode {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "seed";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash8;
  config?: SeedConfig;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo8;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs15;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  root_path?: string | null;
  depends_on?: MacroDependsOn;
  defer_relation?: DeferRelation2 | null;
}
export interface FileHash8 {
  name: string;
  checksum: string;
}
export interface SeedConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook12[];
  "pre-hook"?: Hook13[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs14;
  contract?: ContractConfig6;
  delimiter?: string;
  quote_columns?: boolean | null;
  [k: string]: unknown;
}
export interface Hook12 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook13 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs14 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig6 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo8 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint8[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint8 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs15 {
  show?: boolean;
  node_color?: string | null;
}
export interface MacroDependsOn {
  macros?: string[];
}
export interface DeferRelation2 {
  database: string | null;
  schema: string;
  alias: string;
  relation_name: string | null;
}
export interface SourceDefinition {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "source";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  source_name: string;
  source_description: string;
  loader: string;
  identifier: string;
  _event_status?: {
    [k: string]: unknown;
  };
  quoting?: Quoting;
  loaded_at_field?: string | null;
  freshness?: FreshnessThreshold | null;
  external?: ExternalTable | null;
  description?: string;
  columns?: {
    [k: string]: ColumnInfo9;
  };
  meta?: {
    [k: string]: unknown;
  };
  source_meta?: {
    [k: string]: unknown;
  };
  tags?: string[];
  config?: SourceConfig;
  patch_path?: string | null;
  unrendered_config?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  created_at?: number;
}
export interface Quoting {
  database?: boolean | null;
  schema?: boolean | null;
  identifier?: boolean | null;
  column?: boolean | null;
}
export interface FreshnessThreshold {
  warn_after?: Time | null;
  error_after?: Time1 | null;
  filter?: string | null;
}
export interface Time {
  count?: number | null;
  period?: ("minute" | "hour" | "day") | null;
}
export interface Time1 {
  count?: number | null;
  period?: ("minute" | "hour" | "day") | null;
}
export interface ExternalTable {
  _extra?: {
    [k: string]: unknown;
  };
  location?: string | null;
  file_format?: string | null;
  row_format?: string | null;
  tbl_properties?: string | null;
  partitions?: string[] | ExternalPartition[] | null;
  [k: string]: unknown;
}
export interface ExternalPartition {
  _extra?: {
    [k: string]: unknown;
  };
  name?: string;
  description?: string;
  data_type?: string;
  meta?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnInfo9 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint9[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint9 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface SourceConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  [k: string]: unknown;
}
export interface Macro {
  name: string;
  resource_type: "macro";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  macro_sql: string;
  depends_on?: MacroDependsOn1;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  docs?: Docs16;
  patch_path?: string | null;
  arguments?: MacroArgument[];
  created_at?: number;
  supported_languages?: ("python" | "sql")[] | null;
}
export interface MacroDependsOn1 {
  macros?: string[];
}
export interface Docs16 {
  show?: boolean;
  node_color?: string | null;
}
export interface MacroArgument {
  name: string;
  type?: string | null;
  description?: string;
}
export interface Documentation {
  name: string;
  resource_type: "doc";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  block_contents: string;
}
export interface Exposure {
  name: string;
  resource_type: "exposure";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  type: "dashboard" | "notebook" | "analysis" | "ml" | "application";
  owner: Owner;
  description?: string;
  label?: string | null;
  maturity?: ("low" | "medium" | "high") | null;
  meta?: {
    [k: string]: unknown;
  };
  tags?: string[];
  config?: ExposureConfig;
  unrendered_config?: {
    [k: string]: unknown;
  };
  url?: string | null;
  depends_on?: DependsOn8;
  refs?: RefArgs8[];
  sources?: string[][];
  metrics?: string[][];
  created_at?: number;
}
export interface Owner {
  _extra?: {
    [k: string]: unknown;
  };
  email?: string | null;
  name?: string | null;
  [k: string]: unknown;
}
export interface ExposureConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  [k: string]: unknown;
}
export interface DependsOn8 {
  macros?: string[];
  nodes?: string[];
}
export interface RefArgs8 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface Metric {
  name: string;
  resource_type: "metric";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  description: string;
  label: string;
  type: "simple" | "ratio" | "cumulative" | "derived" | "conversion";
  type_params: MetricTypeParams;
  filter?: WhereFilterIntersection7 | null;
  metadata?: SourceFileMetadata | null;
  meta?: {
    [k: string]: unknown;
  };
  tags?: string[];
  config?: MetricConfig;
  unrendered_config?: {
    [k: string]: unknown;
  };
  sources?: string[][];
  depends_on?: DependsOn9;
  refs?: RefArgs9[];
  metrics?: string[][];
  created_at?: number;
  group?: string | null;
}
export interface MetricTypeParams {
  measure?: MetricInputMeasure | null;
  input_measures?: MetricInputMeasure1[];
  numerator?: MetricInput | null;
  denominator?: MetricInput1 | null;
  expr?: string | null;
  window?: MetricTimeWindow2 | null;
  grain_to_date?: ("day" | "week" | "month" | "quarter" | "year") | null;
  metrics?: MetricInput2[] | null;
  conversion_type_params?: ConversionTypeParams | null;
}
export interface MetricInputMeasure {
  name: string;
  filter?: WhereFilterIntersection | null;
  alias?: string | null;
  join_to_timespine?: boolean;
  fill_nulls_with?: number | null;
}
export interface WhereFilterIntersection {
  where_filters: WhereFilter[];
}
export interface WhereFilter {
  where_sql_template: string;
}
export interface MetricInputMeasure1 {
  name: string;
  filter?: WhereFilterIntersection1 | null;
  alias?: string | null;
  join_to_timespine?: boolean;
  fill_nulls_with?: number | null;
}
export interface WhereFilterIntersection1 {
  where_filters: WhereFilter1[];
}
export interface WhereFilter1 {
  where_sql_template: string;
}
export interface MetricInput {
  name: string;
  filter?: WhereFilterIntersection2 | null;
  alias?: string | null;
  offset_window?: MetricTimeWindow | null;
  offset_to_grain?: ("day" | "week" | "month" | "quarter" | "year") | null;
}
export interface WhereFilterIntersection2 {
  where_filters: WhereFilter2[];
}
export interface WhereFilter2 {
  where_sql_template: string;
}
export interface MetricTimeWindow {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface MetricInput1 {
  name: string;
  filter?: WhereFilterIntersection3 | null;
  alias?: string | null;
  offset_window?: MetricTimeWindow1 | null;
  offset_to_grain?: ("day" | "week" | "month" | "quarter" | "year") | null;
}
export interface WhereFilterIntersection3 {
  where_filters: WhereFilter3[];
}
export interface WhereFilter3 {
  where_sql_template: string;
}
export interface MetricTimeWindow1 {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface MetricTimeWindow2 {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface MetricInput2 {
  name: string;
  filter?: WhereFilterIntersection4 | null;
  alias?: string | null;
  offset_window?: MetricTimeWindow3 | null;
  offset_to_grain?: ("day" | "week" | "month" | "quarter" | "year") | null;
}
export interface WhereFilterIntersection4 {
  where_filters: WhereFilter4[];
}
export interface WhereFilter4 {
  where_sql_template: string;
}
export interface MetricTimeWindow3 {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface ConversionTypeParams {
  base_measure: MetricInputMeasure2;
  conversion_measure: MetricInputMeasure3;
  entity: string;
  calculation?: "conversions" | "conversion_rate";
  window?: MetricTimeWindow4 | null;
  constant_properties?: ConstantPropertyInput[] | null;
}
export interface MetricInputMeasure2 {
  name: string;
  filter?: WhereFilterIntersection5 | null;
  alias?: string | null;
  join_to_timespine?: boolean;
  fill_nulls_with?: number | null;
}
export interface WhereFilterIntersection5 {
  where_filters: WhereFilter5[];
}
export interface WhereFilter5 {
  where_sql_template: string;
}
export interface MetricInputMeasure3 {
  name: string;
  filter?: WhereFilterIntersection6 | null;
  alias?: string | null;
  join_to_timespine?: boolean;
  fill_nulls_with?: number | null;
}
export interface WhereFilterIntersection6 {
  where_filters: WhereFilter6[];
}
export interface WhereFilter6 {
  where_sql_template: string;
}
export interface MetricTimeWindow4 {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface ConstantPropertyInput {
  base_property: string;
  conversion_property: string;
}
export interface WhereFilterIntersection7 {
  where_filters: WhereFilter7[];
}
export interface WhereFilter7 {
  where_sql_template: string;
}
export interface SourceFileMetadata {
  repo_file_path: string;
  file_slice: FileSlice;
}
export interface FileSlice {
  filename: string;
  content: string;
  start_line_number: number;
  end_line_number: number;
}
export interface MetricConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  group?: string | null;
  [k: string]: unknown;
}
export interface DependsOn9 {
  macros?: string[];
  nodes?: string[];
}
export interface RefArgs9 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface Group {
  name: string;
  resource_type: "group";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  owner: Owner1;
}
export interface Owner1 {
  _extra?: {
    [k: string]: unknown;
  };
  email?: string | null;
  name?: string | null;
  [k: string]: unknown;
}
export interface AnalysisNode1 {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "analysis";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash9;
  config?: NodeConfig4;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo10;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs18;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs10[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn10;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE8[];
  _pre_injected_sql?: string | null;
  contract?: Contract8;
}
export interface FileHash9 {
  name: string;
  checksum: string;
}
export interface NodeConfig4 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook14[];
  "pre-hook"?: Hook15[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs17;
  contract?: ContractConfig7;
  [k: string]: unknown;
}
export interface Hook14 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook15 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs17 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig7 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo10 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint10[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint10 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs18 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs10 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn10 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE8 {
  id: string;
  sql: string;
}
export interface Contract8 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface SingularTestNode1 {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "test";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash10;
  config?: TestConfig2;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo11;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs19;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs11[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn11;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE9[];
  _pre_injected_sql?: string | null;
  contract?: Contract9;
}
export interface FileHash10 {
  name: string;
  checksum: string;
}
export interface TestConfig2 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  severity?: string;
  store_failures?: boolean | null;
  store_failures_as?: string | null;
  where?: string | null;
  limit?: number | null;
  fail_calc?: string;
  warn_if?: string;
  error_if?: string;
  [k: string]: unknown;
}
export interface ColumnInfo11 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint11[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint11 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs19 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs11 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn11 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE9 {
  id: string;
  sql: string;
}
export interface Contract9 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface HookNode1 {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "operation";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash11;
  config?: NodeConfig5;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo12;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs21;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs12[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn12;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE10[];
  _pre_injected_sql?: string | null;
  contract?: Contract10;
  index?: number | null;
}
export interface FileHash11 {
  name: string;
  checksum: string;
}
export interface NodeConfig5 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook16[];
  "pre-hook"?: Hook17[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs20;
  contract?: ContractConfig8;
  [k: string]: unknown;
}
export interface Hook16 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook17 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs20 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig8 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo12 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint12[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint12 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs21 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs12 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn12 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE10 {
  id: string;
  sql: string;
}
export interface Contract10 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface ModelNode1 {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "model";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash12;
  config?: ModelConfig1;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo13;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs23;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs13[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn13;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE11[];
  _pre_injected_sql?: string | null;
  contract?: Contract11;
  access?: "private" | "protected" | "public";
  constraints?: ModelLevelConstraint1[];
  version?: string | number | null;
  latest_version?: string | number | null;
  deprecation_date?: string | null;
  defer_relation?: DeferRelation3 | null;
}
export interface FileHash12 {
  name: string;
  checksum: string;
}
export interface ModelConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook18[];
  "pre-hook"?: Hook19[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs22;
  contract?: ContractConfig9;
  access?: "private" | "protected" | "public";
  [k: string]: unknown;
}
export interface Hook18 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook19 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs22 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig9 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo13 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint13[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint13 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs23 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs13 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn13 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE11 {
  id: string;
  sql: string;
}
export interface Contract11 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface ModelLevelConstraint1 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
  columns?: string[];
}
export interface DeferRelation3 {
  database: string | null;
  schema: string;
  alias: string;
  relation_name: string | null;
}
export interface RPCNode1 {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "rpc";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash13;
  config?: NodeConfig6;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo14;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs25;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs14[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn14;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE12[];
  _pre_injected_sql?: string | null;
  contract?: Contract12;
}
export interface FileHash13 {
  name: string;
  checksum: string;
}
export interface NodeConfig6 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook20[];
  "pre-hook"?: Hook21[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs24;
  contract?: ContractConfig10;
  [k: string]: unknown;
}
export interface Hook20 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook21 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs24 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig10 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo14 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint14[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint14 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs25 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs14 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn14 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE12 {
  id: string;
  sql: string;
}
export interface Contract12 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface SqlNode1 {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "sql_operation";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash14;
  config?: NodeConfig7;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo15;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs27;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs15[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn15;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE13[];
  _pre_injected_sql?: string | null;
  contract?: Contract13;
}
export interface FileHash14 {
  name: string;
  checksum: string;
}
export interface NodeConfig7 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook22[];
  "pre-hook"?: Hook23[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs26;
  contract?: ContractConfig11;
  [k: string]: unknown;
}
export interface Hook22 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook23 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs26 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig11 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo15 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint15[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint15 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs27 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs15 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn15 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE13 {
  id: string;
  sql: string;
}
export interface Contract13 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface GenericTestNode1 {
  test_metadata: TestMetadata1;
  database: string | null;
  schema: string;
  name: string;
  resource_type: "test";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash15;
  config?: TestConfig3;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo16;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs28;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs16[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn16;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE14[];
  _pre_injected_sql?: string | null;
  contract?: Contract14;
  column_name?: string | null;
  file_key_name?: string | null;
  attached_node?: string | null;
}
export interface TestMetadata1 {
  name: string;
  kwargs?: {
    [k: string]: unknown;
  };
  namespace?: string | null;
}
export interface FileHash15 {
  name: string;
  checksum: string;
}
export interface TestConfig3 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  severity?: string;
  store_failures?: boolean | null;
  store_failures_as?: string | null;
  where?: string | null;
  limit?: number | null;
  fail_calc?: string;
  warn_if?: string;
  error_if?: string;
  [k: string]: unknown;
}
export interface ColumnInfo16 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint16[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint16 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs28 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs16 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn16 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE14 {
  id: string;
  sql: string;
}
export interface Contract14 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface SnapshotNode1 {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "snapshot";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash16;
  config: SnapshotConfig1;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo17;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs30;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  language?: string;
  refs?: RefArgs17[];
  sources?: string[][];
  metrics?: string[][];
  depends_on?: DependsOn17;
  compiled_path?: string | null;
  compiled?: boolean;
  compiled_code?: string | null;
  extra_ctes_injected?: boolean;
  extra_ctes?: InjectedCTE15[];
  _pre_injected_sql?: string | null;
  contract?: Contract15;
  defer_relation?: DeferRelation4 | null;
}
export interface FileHash16 {
  name: string;
  checksum: string;
}
export interface SnapshotConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook24[];
  "pre-hook"?: Hook25[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs29;
  contract?: ContractConfig12;
  strategy?: string | null;
  target_schema?: string | null;
  target_database?: string | null;
  updated_at?: string | null;
  check_cols?: string | string[] | null;
  [k: string]: unknown;
}
export interface Hook24 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook25 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs29 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig12 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo17 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint17[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint17 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs30 {
  show?: boolean;
  node_color?: string | null;
}
export interface RefArgs17 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface DependsOn17 {
  macros?: string[];
  nodes?: string[];
}
export interface InjectedCTE15 {
  id: string;
  sql: string;
}
export interface Contract15 {
  enforced?: boolean;
  alias_types?: boolean;
  checksum?: string | null;
}
export interface DeferRelation4 {
  database: string | null;
  schema: string;
  alias: string;
  relation_name: string | null;
}
export interface SeedNode1 {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "seed";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  alias: string;
  checksum: FileHash17;
  config?: SeedConfig1;
  _event_status?: {
    [k: string]: unknown;
  };
  tags?: string[];
  description?: string;
  columns?: {
    [k: string]: ColumnInfo18;
  };
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  docs?: Docs32;
  patch_path?: string | null;
  build_path?: string | null;
  deferred?: boolean;
  unrendered_config?: {
    [k: string]: unknown;
  };
  created_at?: number;
  config_call_dict?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  raw_code?: string;
  root_path?: string | null;
  depends_on?: MacroDependsOn2;
  defer_relation?: DeferRelation5 | null;
}
export interface FileHash17 {
  name: string;
  checksum: string;
}
export interface SeedConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  alias?: string | null;
  schema?: string | null;
  database?: string | null;
  tags?: string[] | string;
  meta?: {
    [k: string]: unknown;
  };
  group?: string | null;
  materialized?: string;
  incremental_strategy?: string | null;
  persist_docs?: {
    [k: string]: unknown;
  };
  "post-hook"?: Hook26[];
  "pre-hook"?: Hook27[];
  quoting?: {
    [k: string]: unknown;
  };
  column_types?: {
    [k: string]: unknown;
  };
  full_refresh?: boolean | null;
  unique_key?: string | string[] | null;
  on_schema_change?: string | null;
  on_configuration_change?: "apply" | "continue" | "fail";
  grants?: {
    [k: string]: unknown;
  };
  packages?: string[];
  docs?: Docs31;
  contract?: ContractConfig13;
  delimiter?: string;
  quote_columns?: boolean | null;
  [k: string]: unknown;
}
export interface Hook26 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Hook27 {
  sql: string;
  transaction?: boolean;
  index?: number | null;
}
export interface Docs31 {
  show?: boolean;
  node_color?: string | null;
}
export interface ContractConfig13 {
  enforced?: boolean;
  alias_types?: boolean;
}
export interface ColumnInfo18 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint18[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint18 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface Docs32 {
  show?: boolean;
  node_color?: string | null;
}
export interface MacroDependsOn2 {
  macros?: string[];
}
export interface DeferRelation5 {
  database: string | null;
  schema: string;
  alias: string;
  relation_name: string | null;
}
export interface SourceDefinition1 {
  database: string | null;
  schema: string;
  name: string;
  resource_type: "source";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  source_name: string;
  source_description: string;
  loader: string;
  identifier: string;
  _event_status?: {
    [k: string]: unknown;
  };
  quoting?: Quoting1;
  loaded_at_field?: string | null;
  freshness?: FreshnessThreshold1 | null;
  external?: ExternalTable1 | null;
  description?: string;
  columns?: {
    [k: string]: ColumnInfo19;
  };
  meta?: {
    [k: string]: unknown;
  };
  source_meta?: {
    [k: string]: unknown;
  };
  tags?: string[];
  config?: SourceConfig1;
  patch_path?: string | null;
  unrendered_config?: {
    [k: string]: unknown;
  };
  relation_name?: string | null;
  created_at?: number;
}
export interface Quoting1 {
  database?: boolean | null;
  schema?: boolean | null;
  identifier?: boolean | null;
  column?: boolean | null;
}
export interface FreshnessThreshold1 {
  warn_after?: Time2 | null;
  error_after?: Time3 | null;
  filter?: string | null;
}
export interface Time2 {
  count?: number | null;
  period?: ("minute" | "hour" | "day") | null;
}
export interface Time3 {
  count?: number | null;
  period?: ("minute" | "hour" | "day") | null;
}
export interface ExternalTable1 {
  _extra?: {
    [k: string]: unknown;
  };
  location?: string | null;
  file_format?: string | null;
  row_format?: string | null;
  tbl_properties?: string | null;
  partitions?: string[] | ExternalPartition1[] | null;
  [k: string]: unknown;
}
export interface ExternalPartition1 {
  _extra?: {
    [k: string]: unknown;
  };
  name?: string;
  description?: string;
  data_type?: string;
  meta?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnInfo19 {
  name: string;
  description?: string;
  meta?: {
    [k: string]: unknown;
  };
  data_type?: string | null;
  constraints?: ColumnLevelConstraint19[];
  quote?: boolean | null;
  tags?: string[];
  _extra?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ColumnLevelConstraint19 {
  type:
    | "check"
    | "not_null"
    | "unique"
    | "primary_key"
    | "foreign_key"
    | "custom";
  name?: string | null;
  expression?: string | null;
  warn_unenforced?: boolean;
  warn_unsupported?: boolean;
}
export interface SourceConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  [k: string]: unknown;
}
export interface Exposure1 {
  name: string;
  resource_type: "exposure";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  type: "dashboard" | "notebook" | "analysis" | "ml" | "application";
  owner: Owner2;
  description?: string;
  label?: string | null;
  maturity?: ("low" | "medium" | "high") | null;
  meta?: {
    [k: string]: unknown;
  };
  tags?: string[];
  config?: ExposureConfig1;
  unrendered_config?: {
    [k: string]: unknown;
  };
  url?: string | null;
  depends_on?: DependsOn18;
  refs?: RefArgs18[];
  sources?: string[][];
  metrics?: string[][];
  created_at?: number;
}
export interface Owner2 {
  _extra?: {
    [k: string]: unknown;
  };
  email?: string | null;
  name?: string | null;
  [k: string]: unknown;
}
export interface ExposureConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  [k: string]: unknown;
}
export interface DependsOn18 {
  macros?: string[];
  nodes?: string[];
}
export interface RefArgs18 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface Metric1 {
  name: string;
  resource_type: "metric";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  description: string;
  label: string;
  type: "simple" | "ratio" | "cumulative" | "derived" | "conversion";
  type_params: MetricTypeParams1;
  filter?: WhereFilterIntersection15 | null;
  metadata?: SourceFileMetadata1 | null;
  meta?: {
    [k: string]: unknown;
  };
  tags?: string[];
  config?: MetricConfig1;
  unrendered_config?: {
    [k: string]: unknown;
  };
  sources?: string[][];
  depends_on?: DependsOn19;
  refs?: RefArgs19[];
  metrics?: string[][];
  created_at?: number;
  group?: string | null;
}
export interface MetricTypeParams1 {
  measure?: MetricInputMeasure4 | null;
  input_measures?: MetricInputMeasure5[];
  numerator?: MetricInput3 | null;
  denominator?: MetricInput4 | null;
  expr?: string | null;
  window?: MetricTimeWindow7 | null;
  grain_to_date?: ("day" | "week" | "month" | "quarter" | "year") | null;
  metrics?: MetricInput5[] | null;
  conversion_type_params?: ConversionTypeParams1 | null;
}
export interface MetricInputMeasure4 {
  name: string;
  filter?: WhereFilterIntersection8 | null;
  alias?: string | null;
  join_to_timespine?: boolean;
  fill_nulls_with?: number | null;
}
export interface WhereFilterIntersection8 {
  where_filters: WhereFilter8[];
}
export interface WhereFilter8 {
  where_sql_template: string;
}
export interface MetricInputMeasure5 {
  name: string;
  filter?: WhereFilterIntersection9 | null;
  alias?: string | null;
  join_to_timespine?: boolean;
  fill_nulls_with?: number | null;
}
export interface WhereFilterIntersection9 {
  where_filters: WhereFilter9[];
}
export interface WhereFilter9 {
  where_sql_template: string;
}
export interface MetricInput3 {
  name: string;
  filter?: WhereFilterIntersection10 | null;
  alias?: string | null;
  offset_window?: MetricTimeWindow5 | null;
  offset_to_grain?: ("day" | "week" | "month" | "quarter" | "year") | null;
}
export interface WhereFilterIntersection10 {
  where_filters: WhereFilter10[];
}
export interface WhereFilter10 {
  where_sql_template: string;
}
export interface MetricTimeWindow5 {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface MetricInput4 {
  name: string;
  filter?: WhereFilterIntersection11 | null;
  alias?: string | null;
  offset_window?: MetricTimeWindow6 | null;
  offset_to_grain?: ("day" | "week" | "month" | "quarter" | "year") | null;
}
export interface WhereFilterIntersection11 {
  where_filters: WhereFilter11[];
}
export interface WhereFilter11 {
  where_sql_template: string;
}
export interface MetricTimeWindow6 {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface MetricTimeWindow7 {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface MetricInput5 {
  name: string;
  filter?: WhereFilterIntersection12 | null;
  alias?: string | null;
  offset_window?: MetricTimeWindow8 | null;
  offset_to_grain?: ("day" | "week" | "month" | "quarter" | "year") | null;
}
export interface WhereFilterIntersection12 {
  where_filters: WhereFilter12[];
}
export interface WhereFilter12 {
  where_sql_template: string;
}
export interface MetricTimeWindow8 {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface ConversionTypeParams1 {
  base_measure: MetricInputMeasure6;
  conversion_measure: MetricInputMeasure7;
  entity: string;
  calculation?: "conversions" | "conversion_rate";
  window?: MetricTimeWindow9 | null;
  constant_properties?: ConstantPropertyInput1[] | null;
}
export interface MetricInputMeasure6 {
  name: string;
  filter?: WhereFilterIntersection13 | null;
  alias?: string | null;
  join_to_timespine?: boolean;
  fill_nulls_with?: number | null;
}
export interface WhereFilterIntersection13 {
  where_filters: WhereFilter13[];
}
export interface WhereFilter13 {
  where_sql_template: string;
}
export interface MetricInputMeasure7 {
  name: string;
  filter?: WhereFilterIntersection14 | null;
  alias?: string | null;
  join_to_timespine?: boolean;
  fill_nulls_with?: number | null;
}
export interface WhereFilterIntersection14 {
  where_filters: WhereFilter14[];
}
export interface WhereFilter14 {
  where_sql_template: string;
}
export interface MetricTimeWindow9 {
  count: number;
  granularity: "day" | "week" | "month" | "quarter" | "year";
}
export interface ConstantPropertyInput1 {
  base_property: string;
  conversion_property: string;
}
export interface WhereFilterIntersection15 {
  where_filters: WhereFilter15[];
}
export interface WhereFilter15 {
  where_sql_template: string;
}
export interface SourceFileMetadata1 {
  repo_file_path: string;
  file_slice: FileSlice1;
}
export interface FileSlice1 {
  filename: string;
  content: string;
  start_line_number: number;
  end_line_number: number;
}
export interface MetricConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  group?: string | null;
  [k: string]: unknown;
}
export interface DependsOn19 {
  macros?: string[];
  nodes?: string[];
}
export interface RefArgs19 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface SavedQuery {
  name: string;
  resource_type:
    | "model"
    | "analysis"
    | "test"
    | "snapshot"
    | "operation"
    | "seed"
    | "rpc"
    | "sql_operation"
    | "doc"
    | "source"
    | "macro"
    | "exposure"
    | "metric"
    | "group"
    | "saved_query"
    | "semantic_model";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  query_params: QueryParams;
  exports: Export[];
  _event_status?: {
    [k: string]: unknown;
  };
  description?: string | null;
  label?: string | null;
  metadata?: SourceFileMetadata2 | null;
  config?: SavedQueryConfig;
  unrendered_config?: {
    [k: string]: unknown;
  };
  group?: string | null;
  depends_on?: DependsOn20;
  created_at?: number;
  refs?: RefArgs20[];
}
export interface QueryParams {
  metrics: string[];
  group_by: string[];
  where: WhereFilterIntersection16 | null;
}
export interface WhereFilterIntersection16 {
  where_filters: WhereFilter16[];
}
export interface WhereFilter16 {
  where_sql_template: string;
}
export interface Export {
  name: string;
  config: ExportConfig;
}
export interface ExportConfig {
  export_as: "table" | "view";
  schema_name?: string | null;
  alias?: string | null;
}
export interface SourceFileMetadata2 {
  repo_file_path: string;
  file_slice: FileSlice2;
}
export interface FileSlice2 {
  filename: string;
  content: string;
  start_line_number: number;
  end_line_number: number;
}
export interface SavedQueryConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  group?: string | null;
  meta?: {
    [k: string]: unknown;
  };
  export_as?: ("table" | "view") | null;
  schema?: string | null;
  [k: string]: unknown;
}
export interface DependsOn20 {
  macros?: string[];
  nodes?: string[];
}
export interface RefArgs20 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface SemanticModel {
  name: string;
  resource_type:
    | "model"
    | "analysis"
    | "test"
    | "snapshot"
    | "operation"
    | "seed"
    | "rpc"
    | "sql_operation"
    | "doc"
    | "source"
    | "macro"
    | "exposure"
    | "metric"
    | "group"
    | "saved_query"
    | "semantic_model";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  model: string;
  node_relation: NodeRelation | null;
  description?: string | null;
  label?: string | null;
  defaults?: Defaults | null;
  entities?: Entity[];
  measures?: Measure[];
  dimensions?: Dimension[];
  metadata?: SourceFileMetadata4 | null;
  depends_on?: DependsOn21;
  refs?: RefArgs21[];
  created_at?: number;
  config?: SemanticModelConfig;
  unrendered_config?: {
    [k: string]: unknown;
  };
  primary_entity?: string | null;
  group?: string | null;
}
export interface NodeRelation {
  alias: string;
  schema_name: string;
  database?: string | null;
  relation_name?: string | null;
}
export interface Defaults {
  agg_time_dimension?: string | null;
}
export interface Entity {
  name: string;
  type: "foreign" | "natural" | "primary" | "unique";
  description?: string | null;
  label?: string | null;
  role?: string | null;
  expr?: string | null;
}
export interface Measure {
  name: string;
  agg:
    | "sum"
    | "min"
    | "max"
    | "count_distinct"
    | "sum_boolean"
    | "average"
    | "percentile"
    | "median"
    | "count";
  description?: string | null;
  label?: string | null;
  create_metric?: boolean;
  expr?: string | null;
  agg_params?: MeasureAggregationParameters | null;
  non_additive_dimension?: NonAdditiveDimension | null;
  agg_time_dimension?: string | null;
}
export interface MeasureAggregationParameters {
  percentile?: number | null;
  use_discrete_percentile?: boolean;
  use_approximate_percentile?: boolean;
}
export interface NonAdditiveDimension {
  name: string;
  window_choice:
    | "sum"
    | "min"
    | "max"
    | "count_distinct"
    | "sum_boolean"
    | "average"
    | "percentile"
    | "median"
    | "count";
  window_groupings: string[];
}
export interface Dimension {
  name: string;
  type: "categorical" | "time";
  description?: string | null;
  label?: string | null;
  is_partition?: boolean;
  type_params?: DimensionTypeParams | null;
  expr?: string | null;
  metadata?: SourceFileMetadata3 | null;
}
export interface DimensionTypeParams {
  time_granularity: "day" | "week" | "month" | "quarter" | "year";
  validity_params?: DimensionValidityParams | null;
}
export interface DimensionValidityParams {
  is_start?: boolean;
  is_end?: boolean;
}
export interface SourceFileMetadata3 {
  repo_file_path: string;
  file_slice: FileSlice3;
}
export interface FileSlice3 {
  filename: string;
  content: string;
  start_line_number: number;
  end_line_number: number;
}
export interface SourceFileMetadata4 {
  repo_file_path: string;
  file_slice: FileSlice4;
}
export interface FileSlice4 {
  filename: string;
  content: string;
  start_line_number: number;
  end_line_number: number;
}
export interface DependsOn21 {
  macros?: string[];
  nodes?: string[];
}
export interface RefArgs21 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface SemanticModelConfig {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  group?: string | null;
  meta?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface SavedQuery1 {
  name: string;
  resource_type:
    | "model"
    | "analysis"
    | "test"
    | "snapshot"
    | "operation"
    | "seed"
    | "rpc"
    | "sql_operation"
    | "doc"
    | "source"
    | "macro"
    | "exposure"
    | "metric"
    | "group"
    | "saved_query"
    | "semantic_model";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  query_params: QueryParams1;
  exports: Export1[];
  _event_status?: {
    [k: string]: unknown;
  };
  description?: string | null;
  label?: string | null;
  metadata?: SourceFileMetadata5 | null;
  config?: SavedQueryConfig1;
  unrendered_config?: {
    [k: string]: unknown;
  };
  group?: string | null;
  depends_on?: DependsOn22;
  created_at?: number;
  refs?: RefArgs22[];
}
export interface QueryParams1 {
  metrics: string[];
  group_by: string[];
  where: WhereFilterIntersection17 | null;
}
export interface WhereFilterIntersection17 {
  where_filters: WhereFilter17[];
}
export interface WhereFilter17 {
  where_sql_template: string;
}
export interface Export1 {
  name: string;
  config: ExportConfig1;
}
export interface ExportConfig1 {
  export_as: "table" | "view";
  schema_name?: string | null;
  alias?: string | null;
}
export interface SourceFileMetadata5 {
  repo_file_path: string;
  file_slice: FileSlice5;
}
export interface FileSlice5 {
  filename: string;
  content: string;
  start_line_number: number;
  end_line_number: number;
}
export interface SavedQueryConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  group?: string | null;
  meta?: {
    [k: string]: unknown;
  };
  export_as?: ("table" | "view") | null;
  schema?: string | null;
  [k: string]: unknown;
}
export interface DependsOn22 {
  macros?: string[];
  nodes?: string[];
}
export interface RefArgs22 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface SemanticModel1 {
  name: string;
  resource_type:
    | "model"
    | "analysis"
    | "test"
    | "snapshot"
    | "operation"
    | "seed"
    | "rpc"
    | "sql_operation"
    | "doc"
    | "source"
    | "macro"
    | "exposure"
    | "metric"
    | "group"
    | "saved_query"
    | "semantic_model";
  package_name: string;
  path: string;
  original_file_path: string;
  unique_id: string;
  fqn: string[];
  model: string;
  node_relation: NodeRelation1 | null;
  description?: string | null;
  label?: string | null;
  defaults?: Defaults1 | null;
  entities?: Entity1[];
  measures?: Measure1[];
  dimensions?: Dimension1[];
  metadata?: SourceFileMetadata7 | null;
  depends_on?: DependsOn23;
  refs?: RefArgs23[];
  created_at?: number;
  config?: SemanticModelConfig1;
  unrendered_config?: {
    [k: string]: unknown;
  };
  primary_entity?: string | null;
  group?: string | null;
}
export interface NodeRelation1 {
  alias: string;
  schema_name: string;
  database?: string | null;
  relation_name?: string | null;
}
export interface Defaults1 {
  agg_time_dimension?: string | null;
}
export interface Entity1 {
  name: string;
  type: "foreign" | "natural" | "primary" | "unique";
  description?: string | null;
  label?: string | null;
  role?: string | null;
  expr?: string | null;
}
export interface Measure1 {
  name: string;
  agg:
    | "sum"
    | "min"
    | "max"
    | "count_distinct"
    | "sum_boolean"
    | "average"
    | "percentile"
    | "median"
    | "count";
  description?: string | null;
  label?: string | null;
  create_metric?: boolean;
  expr?: string | null;
  agg_params?: MeasureAggregationParameters1 | null;
  non_additive_dimension?: NonAdditiveDimension1 | null;
  agg_time_dimension?: string | null;
}
export interface MeasureAggregationParameters1 {
  percentile?: number | null;
  use_discrete_percentile?: boolean;
  use_approximate_percentile?: boolean;
}
export interface NonAdditiveDimension1 {
  name: string;
  window_choice:
    | "sum"
    | "min"
    | "max"
    | "count_distinct"
    | "sum_boolean"
    | "average"
    | "percentile"
    | "median"
    | "count";
  window_groupings: string[];
}
export interface Dimension1 {
  name: string;
  type: "categorical" | "time";
  description?: string | null;
  label?: string | null;
  is_partition?: boolean;
  type_params?: DimensionTypeParams1 | null;
  expr?: string | null;
  metadata?: SourceFileMetadata6 | null;
}
export interface DimensionTypeParams1 {
  time_granularity: "day" | "week" | "month" | "quarter" | "year";
  validity_params?: DimensionValidityParams1 | null;
}
export interface DimensionValidityParams1 {
  is_start?: boolean;
  is_end?: boolean;
}
export interface SourceFileMetadata6 {
  repo_file_path: string;
  file_slice: FileSlice6;
}
export interface FileSlice6 {
  filename: string;
  content: string;
  start_line_number: number;
  end_line_number: number;
}
export interface SourceFileMetadata7 {
  repo_file_path: string;
  file_slice: FileSlice7;
}
export interface FileSlice7 {
  filename: string;
  content: string;
  start_line_number: number;
  end_line_number: number;
}
export interface DependsOn23 {
  macros?: string[];
  nodes?: string[];
}
export interface RefArgs23 {
  name: string;
  package?: string | null;
  version?: string | number | null;
}
export interface SemanticModelConfig1 {
  _extra?: {
    [k: string]: unknown;
  };
  enabled?: boolean;
  group?: string | null;
  meta?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
