/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FreshnessExecutionResultArtifact {
  metadata: FreshnessResultsMetadata;
  results: FreshnessResultsNode[];
  elapsed_time: number;
}
export interface FreshnessResultsMetadata {
  dbt_schema_version: string;
  dbt_version: string;
  generated_at: string;
  invocation_id: string;
  invocation_started_at?: string;
  env?: {
    [k: string]: string;
  };
}
export interface FreshnessResultsNode {
  unique_id: string;
  resource_type?: string;
  max_loaded_at: string;
  snapshotted_at: string;
  max_loaded_at_time_ago_in_s: number;
  status: "Pass" | "Warn" | "Error";
  criteria: FreshnessDefinition;
  adapter_response: {
    [k: string]: string;
  };
  timing: TimingInfo[];
  thread_id: string;
  execution_time: number;
}
export interface FreshnessDefinition {
  error_after: FreshnessRules;
  warn_after: FreshnessRules1;
  filter?: string;
  loaded_at_field?: string;
  loaded_at_query?: string;
}
export interface FreshnessRules {
  count: number | null;
  period: ("second" | "minute" | "hour" | "day") | null;
}
export interface FreshnessRules1 {
  count: number | null;
  period: ("second" | "minute" | "hour" | "day") | null;
}
export interface TimingInfo {
  name: string;
  started_at?: string;
  completed_at?: string;
}
