# Copyright 2025 yu-iskw
# SPDX-License-Identifier: Apache-2.0
# Publishes dbt-artifacts-parser (Apache-2.0). Monorepo licensing: see README.md and LICENSES/README.md.

name: Publish dbt-artifacts-parser

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: publish-dbt-artifacts-parser
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit
      - name: Setup Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          # scope: "@yu-iskw"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Build package
        run: |
          pnpm --filter ./packages/dbt-artifacts-parser build
      - name: Run tests
        run: |
          pnpm --filter ./packages/dbt-artifacts-parser test
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm publish --filter ./packages/dbt-artifacts-parser --no-git-checks --access public
